### PR TITLE
respect `+` encoded spaces in parse, wrap encode/decode in try/catch

### PR DESCRIPTION
**Pull request by sperand-io**
Backstory for this is [here](https://github.com/segmentio/analytics.js/issues/470). No pressure to accept, but interested in getting some perspective from the component folks on whether this makes sense to add here. Thoughts?

I've also been advised that wrapping `encodeURIComponent`/`decodeURIComponent` is a best practice, since it can throw. Happy to remove that though if it's contentious :)

Thanks!

### CODE REVIEW

**Comment by sperand-io** [comment]
@stephenmathieson @yields @TooTallNate @jonathanong the gentlest nudge on this for thoughts if you have any (assuming you're the correct folks to ask — feel free to ignore otherwise). thanks a ton in advance!

**Comment by stephenmathieson** [comment]
node's [`querystring.parse()`](https://github.com/joyent/node/blob/master/test/simple/test-querystring.js#L38-L40) already handles the `+` stuff, so I'm +1 on on change.

The `try/catch` stuff I'm also +1 for as `decodeURIComponent` bitten me before.

**Comment by yields** [comment]
i had to do the same in [component/cookie](https://github.com/component/cookie/blob/master/index.js#L109-L131),  +1 !!

**Comment by stephenmathieson** [comment]
`2.0.0` :)

**Comment by sperand-io** [comment]
woot! thanks so much @stephenmathieson

**Pull request merged**
